### PR TITLE
v2.3: Start of implementing caching for get methods.

### PR DESCRIPTION
**Pull request by Andre601**
[Caffeine]: https://github.com/ben-manes/caffeine

This implements caching through the usage of the [Caffeine] library.

The changes affect the `getX()` methods in different ways. Now every time a request is made to the site, the returned JSON is kept for 2 minutes and used for this time before a new request is made.
This should effectively act as a sort of rate limit prevention.

Other changes:
- The provided JSON is no longer a single main field, making the API more threadsafe.
- `getBotlists()` and `getBotlist(String|Site site)` now use an additional String `id`. This is used for the internal cache.

Ideas and improvements are greatly appreciated.
I'll keep this PR open for some time before merging.

### CODE REVIEW

**Comment by DavidRockin** [comment]
Looks cool. Although personally I would separate the caching logic into its own class from the requests. Is there a way to disable caching? It might be useful in development when debugging.

**Comment by Andre601** [comment]
I'll work on this even tho it would be a bad idea to disable it since caching would prevent extreme amounts of requests which at the end could get your bot, program, etc. rate limited.

**Comment by Andre601** [comment]
If no other improvements/ideas are requested, I'll merge it at the end of this week

**Comment by Andre601** [comment]
As announced was this now merged.
Future updates/changes should be made with a separate PR.

**Comment by Andre601** [comment]
@all-contributors bot

**Comment by Andre601** [comment]
@all-contributors please add @DavidRockin for ideas

**Pull request merged**
